yogaRx/Models/ailment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace yogaRx.Models
{
    public class Ailment
    {
        public int AilmentId { get; set; }
        [MaxLength (50)]
        public string AilmentName { get; set; }
        public string AilmentDesc { get; set; }
        public string BodyPartID { get; set; }


        //Navigation
        public virtual ICollection<Pose> Poses { get; set; }
        
    }
}

yogaRx/Controllers/AilmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using yogaRx.Models;

namespace yogaRx.Controllers
{
    public class AilmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [AllowAnonymous]
        public ActionResult HeadFilter()
        {
            var ailments = from item in db.Ailments
                           where item.BodyPartID.Contains("Head")
                           select item;



            return View(ailments.ToList());

        }
        [AllowAnonymous]
        public ActionResult TrunkFilter()
        {
            var ailments = from item in db.Ailments
                           where item.BodyPartID.Contains("Trunk")
                           select item;

            return View(ailments.ToList());
        }
        [AllowAnonymous]
        public ActionResult ArmFilter()
        {
            var ailments = from item in db.Ailments
                           where item.BodyPartID.Contains("Arms")
                           select item;

            return View(ailments.ToList());
        }
        [AllowAnonymous]
        public ActionResult LegFilter()
        {
            var ailments = from item in db.Ailments
                           where item.BodyPartID.Contains("Legs")
                           select item;

            return View(ailments.ToList());
        }


        // GET: Ailments
        [AllowAnonymous]
        public ActionResult Index(string search)
        
        {
            var ailments = from item in db.Ailments
                           //orderby item 
                           select item;

            // filter
            if (!String.IsNullOrEmpty(search))
            {
                ailments = from item in ailments
                           where item.AilmentName.Contains(search)
                           select item;


            }

            return View(ailments.ToList());
        }






        // GET: Ailments/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ailment ailment = db.Ailments.Find(id);
            if (ailment == null)
            {
                return HttpNotFound();
            }

            //var firstPose = ailment.Poses.Single(p => p.PoseName == "Child's Pose");
            //var firstPoseRatings = db.Ratings.Where(r => r.PoseId == firstPose.PoseId);
            //double? score = db.Ratings.Where(r => r.PoseId == firstPose.PoseId).Average(r => r.SymbolRating);



            var poses = from p in ailment.Poses
                        let Score = db.Ratings.Where(r => r.PoseId == p.PoseId).Average(r => r.SymbolRating)
                        orderby Score descending
                        select new Pose
                        {
                            PoseId = p.PoseId,
                            PoseName = p.PoseName,
                            PoseDesc = p.PoseDesc,
                            Photo = p.Photo,
                            Photo1 = p.Photo1,
                            //Score = db.Ratings.Where(r => r.PoseId == p.PoseId).Average(r => r.SymbolRating)
                            Score = Score

                        };

            

            ViewBag.Poses = poses;
            return View(ailment);
        }

        // GET: Ailments/Create
        [Authorize(Roles = "canEdit")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ailments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AilmentId,AilmentName,AilmentDesc")] Ailment ailment)
        {
            if (ModelState.IsValid)
            {
                db.Ailments.Add(ailment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ailment);
        }

        // GET: Ailments/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ailment ailment = db.Ailments.Find(id);
            if (ailment == null)
            {
                return HttpNotFound();
            }
            return View(ailment);
        }

        // POST: Ailments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AilmentId,AilmentName,AilmentDesc")] Ailment ailment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ailment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ailment);
        }

        // GET: Ailments/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ailment ailment = db.Ailments.Find(id);
            if (ailment == null)
            {
                return HttpNotFound();
            }
            return View(ailment);
        }

        // POST: Ailments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ailment ailment = db.Ailments.Find(id);
            db.Ailments.Remove(ailment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

yogaRx/Controllers/PosesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using yogaRx.Models;

namespace yogaRx.Controllers
{
    public class PosesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Poses
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Poses.ToList());
        }



        // GET: Poses/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pose pose = db.Poses.Find(id);
            if (pose == null)
            {
                return HttpNotFound();
            }
            return View(pose);
        }

        // GET: Poses/Create
        [Authorize(Roles = "canEdit")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Poses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PoseId,PoseName,PoseDesc,Photo")] Pose pose)
        {
            if (ModelState.IsValid)
            {
                db.Poses.Add(pose);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pose);
        }

        // GET: Poses/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pose pose = db.Poses.Find(id);
            if (pose == null)
            {
                return HttpNotFound();
            }
            return View(pose);
        }

        // POST: Poses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PoseId,PoseName,PoseDesc,Photo")] Pose pose)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pose).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pose);
        }

        // GET: Poses/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pose pose = db.Poses.Find(id);
            if (pose == null)
            {
                return HttpNotFound();
            }
            return View(pose);
        }

        // POST: Poses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pose pose = db.Poses.Find(id);
            db.Poses.Remove(pose);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

yogaRx/Views/Ailments/ArmFilter.cshtml
@model IEnumerable<yogaRx.Models.Ailment>

@{
    ViewBag.Title = "Arms";
}

<h2>Arms</h2>


@foreach (var item in Model)
{

    <ul>
        <li>
            <div>
                <h4>
                    @Html.ActionLink(item.AilmentName, "Details", "Ailments", new { id = item.AilmentId }, null)
                </h4>
            </div>
        </li>
    </ul>

            @*@Html.ActionLink("Edit", "Edit", new { id=item.AilmentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AilmentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AilmentId })*@
     
}

yogaRx/Views/Ailments/Create.cshtml
@model yogaRx.Models.Ailment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ailment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AilmentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AilmentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AilmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AilmentDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AilmentDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AilmentDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

yogaRx/Views/Ailments/Delete.cshtml
@model yogaRx.Models.Ailment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ailment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AilmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AilmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AilmentDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AilmentDesc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

yogaRx/Views/Ailments/Details.cshtml
@model yogaRx.Models.Ailment

@{
    ViewBag.Title = "Details";
}




<div>
    <h2>@Html.DisplayFor(model => model.AilmentName)</h2>
    <h5>Pose order determined by number of  <span class="glyphicon glyphicon-thumbs-up"></span>.</h5>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            Ailment
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AilmentName)
        </dd>*@
    </dl>

        @foreach (yogaRx.Models.Pose item in ViewBag.Poses)
            {
            @*if (item.Score != null)
                                  {
                                      <div> @item.Score </div>
                }*@
<div>
            <div align="center">
                @Html.ActionLink(item.PoseName, "Details", "Poses", new { id = item.PoseId }, new { @class = "pose-link" })
            </div>

            <div align="center">
                @if (item.Photo != null)
                {
                    <a href="@Url.Action("Details", "Poses", new { id = item.PoseId })" ><img class="small" src="@Url.Content(item.Photo)" /></a>
                }
            </div>
    </div>

            <br>


        }
    <br>
    @{
        ViewBag.SelectablePoses = from item in Model.Poses
                                  select item;

        ViewBag.PoseList = new SelectList(ViewBag.SelectablePoses, "PoseId", "PoseName");
    }
 
    Write a comment:
    @using (Html.BeginForm("PostComment", "Manage", FormMethod.Get))
    {
        @*@Html.AntiForgeryToken()*@
        @Html.Hidden("AilmentId", Model.AilmentId)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Poses, "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PoseList", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Poses, "", new { @class = "text-danger" })
            </div><br>
            <br>


         

            <div>
                <div class="form-group" >
                    <div class="btn-group" data-toggle="buttons">
                        <label class="pdsa-radiobutton btn btn-secondary active">
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            @Html.RadioButton("SymbolRating", "1", new { htmlAttributes = new { @class = "form-control" } })
                        </label>
                        <label class="pdsa-radiobutton btn btn-secondary">
                            <span class="glyphicon glyphicon-thumbs-down"></span>
                            @Html.RadioButton("SymbolRating", "-1",
              new { htmlAttributes = new { @class = "form-control" } })
                        </label>
                    </div>
                </div>
                </div>
            <br>
            

            
     

             @*@Html.TextBoxFor(m => m.Poses, new { @class = "form-control" })*@
            <label for="comment">Comment:</label>
            <textarea type="Text" name="TextReview" class="form-control" rows="5" id="comment"></textarea>
           <input class="btn btn-secondary"  type="submit"  /> 
        </div>

        
    }
    <div>
        @foreach (var pose in Model.Poses)
        {
            foreach (var rating in pose.Ratings)
            {
                if(rating.User != null && rating.Ailment.AilmentName == Model.AilmentName && rating.TextReview != "")
                {                  
                         <u><b> @rating.User.Email</b>  said:</u>
                            <div class="commentbox">
                                @rating.TextReview                               
                            </div>                        
                }
            }
        }
    </div>

</div>

    @*@Html.ActionLink("Edit", "Edit", new { id = Model.AilmentId }) |*@
    <p>@Html.ActionLink("Back to List", "Index")</p>

yogaRx/Views/Ailments/Edit.cshtml
@model yogaRx.Models.Ailment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ailment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AilmentId)

        <div class="form-group">
            @Html.LabelFor(model => model.AilmentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AilmentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AilmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AilmentDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AilmentDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AilmentDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

yogaRx/Views/Ailments/HeadFilter.cshtml
@model IEnumerable<yogaRx.Models.Ailment>

@{
    ViewBag.Title = "Head";
}

<h2>Head</h2>



@foreach (var item in Model)
{

    <ul>
        <li>
            <div>
                <h4>
                    @Html.ActionLink(item.AilmentName, "Details", "Ailments", new { id = item.AilmentId }, null)
                </h4>
            </div>
        </li>
    </ul>


            @*@Html.ActionLink("Edit", "Edit", new { id=item.AilmentId }) |*@
            @*@Html.ActionLink("Details", "Details", new { id=item.AilmentId })*@ 
            @*@Html.ActionLink("Delete", "Delete", new { id=item.AilmentId })*@
  
}

yogaRx/Views/Ailments/Index.cshtml
@model IEnumerable<yogaRx.Models.Ailment>

@{
    ViewBag.Title = "AilmentIndex";
}

<h2>Ailments</h2>



@foreach (var item in Model)
{

    <ul>
        <li>
            <div>
                <h4>
                    @Html.ActionLink(item.AilmentName, "Details", "Ailments", new { id = item.AilmentId }, null)
                </h4>
            </div>
        </li>
    </ul>

            @*@Html.ActionLink("Details", "Details", new { id=item.AilmentId })*@ 
           
      
}

yogaRx/Views/Ailments/LegFilter.cshtml
@model IEnumerable<yogaRx.Models.Ailment>

@{
    ViewBag.Title = "Leg";
}

<h2>Legs</h2>


@foreach (var item in Model)
{
    <ul>
        <li>
            <div>
                <h4>
                    @Html.ActionLink(item.AilmentName, "Details", "Ailments", new { id = item.AilmentId }, null)
                </h4>
            </div>
        </li>
    </ul>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.AilmentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AilmentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AilmentId })*@
       
}

yogaRx/Views/Ailments/TrunkFilter.cshtml
@model IEnumerable<yogaRx.Models.Ailment>

@{
    ViewBag.Title = "Trunk";
}

<h2>Trunk</h2>



@foreach (var item in Model)
{
    <ul>
        <li>
            <div>
                <h4>
                    @Html.ActionLink(item.AilmentName, "Details", "Ailments", new { id = item.AilmentId }, null)
                </h4>
            </div>
        </li>
    </ul>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.AilmentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AilmentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AilmentId })*@

}